#!/usr/bin/env python

import os, sys, platform, subprocess
from shutil import copyfile
from distutils.core import setup

desription = 'SEN2THREE is ... \
For details, read the Software \
User Manual which is attached to this python module.',

_name = 'SEN2THREE'

setup (
    name = _name,
    version = '1.0.0',
    description = 'SEN2THREE: Sentinel Level 3 Processor',
    author = 'Telespazio VEGA Deutschland GmbH',
    author_email = 'info@telespazio-vega.de',
    url = 'www.telespazio-vega.de',
    download_url = 'www.telespazio-vega.de',
    platforms=['linux-x86_64', 'macosx-10.5-x86_64', 'win-amd64'],
)

sys.stdout.write('\nSEN2THREE 1.0.0 setup script:\n')
sys.stdout.write('This will setup the operating system dependent parts of the application\n')
sys.stdout.write('and supports you in the proper configuration of the environment settings.\n')
user_input = raw_input('\nOK to continue? [y/n]: ')
if user_input == 'n':
    sys.exit(0)

try:
    path = os.environ['PATH']
    if 'Anaconda' in path == False:
        raise KeyError('ANACONDA')
except KeyError as err:
    if err.args[0] == 'PATH':
        sys.stderr.write('No PATH variable configured.\n\
        Please follow the installation procedure of the user manual\n\
        before continuing ...')
    elif err.args[0] == 'ANACONDA':
        sys.stderr.write('Anaconda seems to be not installed or properly configured.\n\
        Please follow the installation procedure of the user manual\n\
        before continuing ...')    
    sys.exit(-1)

home = os.getcwd()+'/'+_name +'/'
build = home+'build/'
bin = home+'bin/'
src = home+'src/'
bind = home+'bin'
logd = home+'log'

if not os.path.exists(bind):
    os.makedirs(bind)

if not os.path.exists(logd):
    os.makedirs(logd)

if not os.path.exists(src):
    sys.stderr.write('Directory % does not exist!' % src)
    sys.exit(-1)

system = platform.system()
if system == 'Windows':
    fn = 'geojasper.exe'
    copyfile(build+fn, bin+fn)

    L3_Process = '@echo off\n'
    L3_Process += ':: SEN2THREE environmental setup, version 2.0.0\n'
    L3_Process += ':: settings automatically generated by setup.py\n\n'
    L3_Process += 'cd %S2L3APPHOME%\n'
    L3_Process += 'python %S2L3APPHOME%\src\L3_Process.py %1 %2 %3 %4\n'
    L3_Process += '@echo on\n'    

    textFile = open(bin+'L3_Process.bat', "w")
    textFile.write(L3_Process)
    textFile.close()

elif (system == 'Linux') or (system == 'Darwin'):
    # Unlock files for editing:
    for root, dirs, files in os.walk(home, topdown=False):
        for fn in files:
            fn = root + '/' + fn
            os.chmod(fn, 0666)

    break_condition = True
    while True:
        # setting the environments for the application into L3_Bashrc:
        L3_Bashrc = '#!/usr/bin/env bash\n'
        L3_Bashrc += '# SEN2THREE environmental setup, version 2.0.0\n'
        L3_Bashrc += '# settings automatically generated by setup.py\n\n'
        L3_Bashrc += 'export S2L3APPHOME=${PWD}\n'
        L3_Bashrc += 'export S2L3APPCFG=$S2L3APPHOME/cfg\n'
        L3_Bashrc += 'export PATH=$S2L3APPHOME/bin:$PATH\n'
    
        if system == 'Linux':
            if break_condition == True:
                gdalBinaries = '/usr/bin'     
                gdalPackages = '/usr/lib64/python2.6/site-packages/osgeo'
                gdalResources = '/usr/share/epsg_csv'        
        elif system == 'Darwin':
            L3_Bashrc += 'export LC_ALL=en_US.UTF-8\n' 
            L3_Bashrc += 'export LANG=en_US.UTF-8\n'
            if break_condition == True:
                gdalBinaries = '/Library/Frameworks/GDAL.framework/Programs'
                gdalPackages = '/Library/Frameworks/GDAL.framework/Versions/Current/Python/2.7/site-packages'
                gdalResources = '/Library/Frameworks/GDAL.framework/Resources'

        break_condition = True
        sys.stdout.write('\nCheck if GDAL binaries are installed and configured:\n')
        try:
            command = gdalBinaries + '/gdalinfo --version'
            if subprocess.call(command, shell=True) != 0:
                raise
        except:
            sys.stdout.write('\nNo GDAL binaries found.\n')
            sys.stdout.write('Current path is:\n')
            sys.stdout.write(gdalBinaries+'\n')
            user_input = raw_input('Is this OK? [y/n]: ')
            if user_input == 'n':
                gdalBinaries = raw_input('New path: ')
            break_condition = False
        L3_Bashrc += 'export PATH=$PATH:'+ gdalBinaries + '\n'
                
        sys.stdout.write('\nCheck if GDAL python bindings are installed and configured:\n')   
        try:
            gdal_py = gdalPackages + '/gdal.py'
            if os.path.isfile(gdal_py):
                sys.stdout.write('GDAL python bindings found.\n')       
            else:
                raise KeyError
        except KeyError:
            sys.stdout.write('No GDAL python bindings found.\n')
            sys.stdout.write('Current path is:\n')
            sys.stdout.write(gdalPackages+'\n')
            user_input = raw_input('Is this OK? [y/n]: ')
            if user_input == 'n':
                gdalPackages = raw_input('New path: ')
            break_condition = False
        L3_Bashrc += 'export PYTHONPATH=$PYTHONPATH:' + gdalPackages + '\n'                
        
        sys.stdout.write('\nCheck if GDAL resources are installed and configured:\n')         
        try:
            gdalData = os.environ['GDAL_DATA']
            if os.path.exists(gdalData) == True:
                sys.stdout.write('GDAL resources are configured via $GDAL_DATA.\n')   
            else:
                raise
        except:
            sys.stdout.write('No GDAL resources configured via $GDAL_DATA.\n')
            sys.stdout.write('Current path is:\n')
            sys.stdout.write(gdalResources+'\n')
            user_input = raw_input('Is this OK? [y/n]: ')
            if user_input == 'n':
                gdalResources = raw_input('New path: ')
            os.environ['GDAL_DATA'] = gdalPackages
            break_condition = False                
        L3_Bashrc += 'export GDAL_DATA='+ gdalResources + '\n'            
        
        if break_condition == True:
            break

    textFile = open(home+'L3_Bashrc', "w")
    textFile.write(L3_Bashrc)
    textFile.close()

    if os.path.exists(libf) == False:
        sys.stderr.write('File % does not exist!' % libf)
        sys.exit(-1)
    srcf = src + fn
    copyfile(libf, srcf)

    if((os.path.isfile(bin+'L3_Process')) == True):
        os.remove(bin+'L3_Process')
    os.symlink(src+'L3_Process.py', bin+'L3_Process')

    # Lock files for write protection:
    for root, dirs, files in os.walk(home, topdown=False):
        for fn in files:
            fn = root + '/' + fn
            os.chmod(fn, 0444)
    os.chmod(home+'L3_Bashrc', 0644)
    os.chmod(src+'L3_Process.py', 0554)

else:
    sys.stderr.wite('Unsupported Operating System,\n\
                     installation not performed!')
    sys.exit(-1)

sys.stdout.write('\nInstallation performed in '+home+'.\n\n') 
if system != 'Windows':    
    sys.stdout.write('All configuration is provided in the L3_Bashrc shell script.\n')
    sys.stdout.write('The script must be sourced either manually \"source L3_Bashrc\",\n')
    sys.stdout.write('or from the users .profile or from the Toolbox start script.\n')

sys.exit(0)

if __name__ == '__main__':
    pass